version: "3"

services:

  marketplace-public:
    image: kinecosystem/marketplace-server:latest
    command: ./tests/wait-for -t 60 marketplace-internal:3000 -- npm run start
    restart: "no"
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    links:
      - redis
      - payment-service
      - postgres
      - bi-service
    environment:
      &app_env_vars
      APP_DEBUG: 'True'
      APP_PORT: 3000
      APP_HOST: '0.0.0.0'
      APP_NAME: 'marketplace-public'
      APP_REDIS: redis://redis:6379/0
      APP_PAYMENT_SERVICE: http://payment-service:3000
      APP_INTERNAL_SERVICE: http://marketplace-internal:3000
      APP_BI_SERVICE: http://bi-service
      APP_DB_TYPE: postgres
      APP_DB_USERNAME: user
      APP_DB_PASSWORD: pass
      APP_DB_PORT: 5432
      APP_DB_HOST: postgres
      APP_DB_DATABASE: ecosystem
      NODEMON_WATCH_DIRS: ${NODEMON_WATCH_DIRS}
      CACHE_TTL: '{ "default": 0 }'

  marketplace-admin:
    image: kinecosystem/marketplace-server:latest
    restart: "no"
    command: ./tests/wait-for -t 60 marketplace-public:3000 -- npm run start-admin
    volumes:
      - .:/opt/app
    ports:
      - 3002:3000
    links:
      - redis
      - payment-service
      - postgres
      - marketplace-public # so I can wait for it
    environment:
      <<: *app_env_vars
      APP_NAME: 'marketplace-admin'

  marketplace-internal:
    image: kinecosystem/marketplace-server:latest
    restart: "no"
    command: ./tests/wait-for -t 60 postgres:5432 -- npm run start-internal
    volumes:
      - .:/opt/app
    ports:
      - 3001:3000
    links:
      - redis
      - payment-service
      - postgres
      - marketplace-public # so I can wait for it
    environment:
      <<: *app_env_vars
      APP_NAME: 'marketplace-internal'
      APP_JWT_KEYS_DIR: /opt/app/jwt

  postgres:
    image: postgres:10.4
    ports:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ecosystem
