version: "3"

services:

  marketplace-server:
    image: kinecosystem/marketplace-server:8de5772
    restart: on-failure
    ports:
      - 3000
    links:
      - redis
      - payment-service
      - postgres
      - bi-service
    environment:
      &app_env_vars
      APP_DEBUG: 'True'
      APP_PORT: 3000
      APP_HOST: '0.0.0.0'
      APP_NAME: 'marketplace-server'
      APP_REDIS: redis://redis:6379/0
      APP_PAYMENT_SERVICE: http://payment-service:3000
      APP_INTERNAL_SERVICE: http://marketplace-internal:3000
      APP_BI_SERVICE: http://bi-service
      APP_DB_TYPE: postgres
      APP_DB_USERNAME: user
      APP_DB_PASSWORD: pass
      APP_DB_PORT: 5432
      APP_DB_HOST: postgres
      APP_DB_DATABASE: ecosystem

  marketplace-admin:
    image: kinecosystem/marketplace-server:6482b4c
    command: npm run start-admin
    ports:
      - 3000
    links:
      - redis
      - payment-service
      - postgres
      - marketplace-server # so I can wait for it
    environment:
      <<: *app_env_vars
      APP_NAME: 'marketplace-internal'

  marketplace-internal:
    image: kinecosystem/marketplace-server:8de5772
    command: npm run start-internal
    ports:
      - 3000
    links:
      - redis
      - payment-service
      - postgres
      - marketplace-server # so I can wait for it
    environment:
      <<: *app_env_vars
      APP_NAME: 'marketplace-internal'
      APP_JWT_KEYS_DIR: /opt/app/jwt

  postgres:
    image: postgres:10.4
    ports:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ecosystem
