version: "3"

services:
  psql:
    image: postgres:10.4
    links:
      - postgres
    entrypoint: psql -h postgres -U user -d ecosystem
    environment:
      PGPASSWORD: pass
  
  redis-cli:
    image: redis:4.0
    links:
      - redis
    entrypoint: redis-cli -h redis -p 6379

  create-db:
    image: kinecosystem/marketplace-server:latest
    volumes:
      - .:/opt/app
    links:
      - postgres
    command: npm run create-db -- data/apps data/offers
    environment:
      APP_DB_TYPE: postgres
      APP_DB_USERNAME: user
      APP_DB_PASSWORD: pass
      APP_DB_PORT: 5432 
      APP_DB_HOST: postgres
      APP_DB_DATABASE: ecosystem
      STELLAR_ADDRESS: ${STELLAR_ADDRESS}

  test-system:
    image: kinecosystem/marketplace-server:latest
    volumes:
      - .:/opt/app
    links:
      - marketplace-server
      - jwt-service
    environment:
      MARKETPLACE_BASE: http://marketplace-server:3000
      JWT_SERVICE_BASE: http://jwt-service:3000
    command: npm run test-system

  generate-funding-address:
    image: kinecosystem/payment-service:577d133
    command: pipenv run python generate_funding_address.py
    volumes:
      - ./secrets:/secrets
    environment:
      OUTPUT_DIR: /secrets
      KIN_FAUCET: 'http://faucet-playground.kininfrastructure.com'
      XLM_FAUCET: 'http://friendbot-playground.kininfrastructure.com'
      STELLAR_HORIZON_URL: 'https://horizon-playground.kininfrastructure.com'
      STELLAR_NETWORK: 'Kin Playground Network ; June 2018'
      STELLAR_KIN_ISSUER_ADDRESS: 'GBC3SG6NGTSZ2OMH3FFGB7UVRQWILW367U4GSOOF4TFSZONV42UJXUH7'
      STELLAR_KIN_TOKEN_NAME: 'KIN'
